[tools]
go = "1.25.1"
golangci-lint = "2.5.0"
buf = "1.58.0"
act = "latest"
"ubi:k1LoW/octocov" = "latest"
ginkgo = "2.25.3"
"go:github.com/aarondl/sqlboiler/v4" = "4.19.5"
"go:github.com/aarondl/sqlboiler/v4/drivers/sqlboiler-mysql" = "4.19.5"
