apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../namespace.yaml
  - db-admin.yaml
  - command-db.yaml
  - query-db.yaml
  - db-replication-job.yaml

configMapGenerator:
  # migrator用のConfigMap
  - name: migrator-scripts
    files:
      - ./scripts/start-replication.sh
