apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cqrs
resources:
  - ../../../base/services

patches:
  - target:
      kind: Deployment
      name: client-service
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: IfNotPresent
  - target:
      kind: Deployment
      name: query-service
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: IfNotPresent
  - target:
      kind: Deployment
      name: command-service
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: IfNotPresent
  - target:
      kind: Gateway
      name: cqrs
    patch: |-
      - op: replace
        path: /spec/gatewayClassName
        value: eg

secretGenerator:
  - name: secret
    envs:
      - ../.env.secret

configMapGenerator:
  # 共通の環境変数用ConfigMap
  - name: config-env
    envs:
      - ../.env.local

images:
  - name: command-service
    newName: cqrs-command_service
    newTag: "latest"
  - name: query-service
    newName: cqrs-query_service
    newTag: "latest"
  - name: client-service
    newName: cqrs-client_service
    newTag: "latest"
