env = "dev"

[log]
level = "debug"
format = "json"

[server]
host = "localhost"
port = 8090

[cqrs]
command_service_url = "http://localhost:8083"
query_service_url = "http://localhost:8085"

request_timeout = "30s"         # リクエストのタイムアウト時間
tcp_timeout = "5s"              # TCP接続のタイムアウト時間
tcp_keep_alive = "30s"          # TCPキープアライブの間隔
tls_handshake_timeout = "10s"   # TLSハンドシェイクのタイムアウト時間
response_header_timeout = "10s" # レスポンスヘッダーのタイムアウト時間
idle_conn_timeout = "90s"       # アイドルコネクションのタイムアウト時間
max_idle_conns = 100            # 最大アイドルコネクション数
max_idle_conns_per_host = 10    # ホストごとの最大アイドルコネクション数
